frr version 10.2.1_git
frr defaults traditional
hostname R1
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config
!
interface eth1
 ip address 10.0.12.1/24
!
interface eth2
 ip address 10.0.14.1/24
!
interface lo
 ip address 1.1.1.1/32
!
rpki
 rpki cache 172.20.20.6 3323 preference 1
 rpki polling_period 30
!
router bgp 65001
 bgp router-id 1.1.1.1
 no bgp ebgp-requires-policy
 no bgp enforce-first-as
 neighbor 10.0.12.2 remote-as 65002
 neighbor 10.0.14.4 remote-as 65004
 !
 address-family ipv4 unicast
  redistribute connected
  neighbor 10.0.12.2 next-hop-self
  neighbor 10.0.14.4 next-hop-self
 exit-address-family
!
line vty
!
