frr version 10.2.1_git
frr defaults traditional
hostname R2
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config
!
interface eth1
 ip address 10.0.12.2/24
!
interface eth2
 ip address 10.0.23.2/24
!
interface eth3
 ip address 10.0.26.2/24
!
interface lo
 ip address 2.2.2.2/32
!
rpki
 rpki cache 172.20.20.6 3323 preference 1
 rpki polling_period 30
!
router bgp 65002
 bgp router-id 2.2.2.2
 no bgp ebgp-requires-policy
 no bgp enforce-first-as
 neighbor 10.0.12.1 remote-as 65001
 neighbor 10.0.23.3 remote-as 65003
 neighbor 10.0.26.6 remote-as 65006
 !
 address-family ipv4 unicast
  neighbor 10.0.12.1 next-hop-self
  neighbor 10.0.23.3 next-hop-self
  neighbor 10.0.26.6 next-hop-self
  redistribute connected
 exit-address-family
!
line vty
!
